<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>k_spider_dotnet</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" Version="1.11.60"/>
        <PackageReference Include="Microsoft.Playwright" Version="1.43.0"/>
        <PackageReference Include="SqlSugarCore" Version="5.1.4.188"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\k-spider-dotnet-lib\k-spider-dotnet-lib.csproj" />
    </ItemGroup>
</Project>
