<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>KSpider.Sync</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Quartz.Extensions.Hosting" />
      <PackageReference Include="SqlSugarCore" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\k-spider-dotnet\k-spider-dotnet.csproj" />
    </ItemGroup>

</Project>
