<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>k_spider_dotnet_lib</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="SqlSugarCore" Version="5.1.4.158"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0"/>
    </ItemGroup>
</Project>
