-- Database export: k_script_spider
-- Date: 2026-09-19 20:50:07
-- Generated by DBX

CREATE EXTENSION IF NOT EXISTS "amcheck" WITH SCHEMA "public";

DROP TABLE IF EXISTS "public"."spider_news_content" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_content_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_content" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300),
  "news_title" character varying(300),
  "news_summary" text,
  "news_from" character varying(100),
  "news_time" timestamp without time zone,
  "news_keyword" text,
  "news_content_json" text,
  "news_content_text" text,
  CONSTRAINT "spider_news_content_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_content_test_url" UNIQUE (news_url)
);
COMMENT ON TABLE "public"."spider_news_content" IS '新闻信息详情表';

DROP TABLE IF EXISTS "public"."spider_news_content_origin" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_content_origin_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_content_origin" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300) NOT NULL,
  "news_origin_content" text,
  "news_origin_type" integer NOT NULL DEFAULT 0,
  "status" integer NOT NULL DEFAULT 0,
  "message" text,
  CONSTRAINT "spider_news_content_origin_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_content_origin_url" UNIQUE (news_url)
);

DROP TABLE IF EXISTS "public"."spider_news_image_list" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_image_list_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_image_list" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300),
  "image_resource_url" character varying(400),
  "image_name" character varying(100),
  CONSTRAINT "spider_news_image_list_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_image_url" UNIQUE (image_resource_url)
);
COMMENT ON TABLE "public"."spider_news_image_list" IS '爬虫详情中的图片信息记录';

DROP TABLE IF EXISTS "public"."spider_news_list" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_list_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_list" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "from_media" integer,
  "news_url" character varying(300),
  "news_title" character varying(300),
  "news_summary" text,
  "news_from" character varying(30),
  "news_time" timestamp without time zone,
  "news_download_time" timestamp without time zone,
  "category" integer NOT NULL DEFAULT 0,
  "download_status_code" integer NOT NULL DEFAULT 0,
  "fail_count" integer NOT NULL DEFAULT 0,
  CONSTRAINT "spider_news_list_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_url" UNIQUE (news_url)
);
COMMENT ON TABLE "public"."spider_news_list" IS '排重抓取信息信息列表';
COMMENT ON COLUMN "public"."spider_news_list"."category" IS '新闻类型';
COMMENT ON COLUMN "public"."spider_news_list"."download_status_code" IS '详情数据是否下载 0 没有下载 1 已下载';
CREATE INDEX "idx_news_list_download_status" ON "public"."spider_news_list" USING btree ("download_status_code", "id") WHERE (download_status_code = ANY (ARRAY[0, 2, 3, 4]));

DROP TABLE IF EXISTS "public"."stock_cn_introduction" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."stock_introduction_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."stock_cn_introduction" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "stock_id" character varying(200),
  "stock_name" character varying(200),
  "exchange_channel" integer,
  CONSTRAINT "stock_cn_introduction_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_stock_cn_introduction" UNIQUE (stock_id)
);

DROP TABLE IF EXISTS "public"."stock_cn_level1_archived_daily_origin" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."stock_cn_level1_archived_daliy_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."stock_cn_level1_archived_daily_origin" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "stock_id" character varying(200) NOT NULL,
  "exchange_channel" integer NOT NULL,
  "date" date NOT NULL,
  "archived" text,
  "data_from" integer,
  CONSTRAINT "stock_cn_level1_archived_daliy_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_cn_daily_stock" UNIQUE (date, stock_id)
);
COMMENT ON TABLE "public"."stock_cn_level1_archived_daily_origin" IS '中国股市信息天级别表归档';
CREATE UNIQUE INDEX "stock_cn_id_date" ON "public"."stock_cn_level1_archived_daily_origin" USING btree ("stock_id", "date");

DROP TABLE IF EXISTS "public"."stock_hk_level1_archived_daily_origin" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."stock_hk_level1_archived_daliy_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."stock_hk_level1_archived_daily_origin" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "stock_id" character varying(200) NOT NULL,
  "exchange_channel" integer NOT NULL,
  "date" date NOT NULL,
  "archived" text,
  "data_from" integer,
  CONSTRAINT "stock_hk_level1_archived_daliy_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_hk_daily_stock" UNIQUE (date, stock_id)
);
COMMENT ON TABLE "public"."stock_hk_level1_archived_daily_origin" IS '香港股市信息天级别level1原始数据';
CREATE UNIQUE INDEX "stock_hk_id_date" ON "public"."stock_hk_level1_archived_daily_origin" USING btree ("stock_id", "date");

DROP TABLE IF EXISTS "public"."stock_usa_level1_archived_daliy_origin" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."stock_usa_level1_archived_daliy_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."stock_usa_level1_archived_daliy_origin" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "stock_id" character varying(200) NOT NULL,
  "exchange_channel" integer NOT NULL,
  "date" date NOT NULL,
  "archived" text,
  "data_from" integer,
  CONSTRAINT "stock_usa_level1_archived_daliy_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_usa_daily_stock" UNIQUE (date, stock_id)
);
COMMENT ON TABLE "public"."stock_usa_level1_archived_daliy_origin" IS '美股股市信息天级别level1归档原始数据';

ALTER SEQUENCE "public"."spider_news_content_id_seq" OWNED BY "public"."spider_news_content"."id";

ALTER SEQUENCE "public"."spider_news_content_origin_id_seq" OWNED BY "public"."spider_news_content_origin"."id";

ALTER SEQUENCE "public"."spider_news_image_list_id_seq" OWNED BY "public"."spider_news_image_list"."id";

ALTER SEQUENCE "public"."spider_news_list_id_seq" OWNED BY "public"."spider_news_list"."id";

ALTER SEQUENCE "public"."stock_cn_level1_archived_daliy_id_seq" OWNED BY "public"."stock_cn_level1_archived_daily_origin"."id";

ALTER SEQUENCE "public"."stock_hk_level1_archived_daliy_id_seq" OWNED BY "public"."stock_hk_level1_archived_daily_origin"."id";

ALTER SEQUENCE "public"."stock_introduction_id_seq" OWNED BY "public"."stock_cn_introduction"."id";

ALTER SEQUENCE "public"."stock_usa_level1_archived_daliy_id_seq" OWNED BY "public"."stock_usa_level1_archived_daliy_origin"."id";

SELECT setval('"public"."spider_news_content_id_seq"', GREATEST(COALESCE(MAX("id"), 1254085), 1254085), true) FROM "public"."spider_news_content";

SELECT setval('"public"."spider_news_content_origin_id_seq"', GREATEST(COALESCE(MAX("id"), 991189), 991189), true) FROM "public"."spider_news_content_origin";

SELECT setval('"public"."spider_news_image_list_id_seq"', GREATEST(COALESCE(MAX("id"), 98564), 98564), true) FROM "public"."spider_news_image_list";

SELECT setval('"public"."spider_news_list_id_seq"', GREATEST(COALESCE(MAX("id"), 990191), 990191), true) FROM "public"."spider_news_list";

CREATE OR REPLACE FUNCTION public.update_time_func()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    NEW.update_time := current_timestamp;
    RETURN NEW;
END;$function$;

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_content FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_content_origin FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_image_list FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_list FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON stock_cn_level1_archived_daily_origin FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_function BEFORE UPDATE ON stock_hk_level1_archived_daily_origin FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_time BEFORE UPDATE ON stock_usa_level1_archived_daliy_origin FOR EACH ROW EXECUTE FUNCTION update_time_func();


--
-- 实时快讯 ( 2026-09 新增 : 列表即全文的快讯源 , 拉到即终态 , 无状态机 )
--

CREATE TABLE IF NOT EXISTS "public"."spider_flash_news" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "from_media" integer NOT NULL,
  "category" integer NOT NULL DEFAULT 0,
  "news_url" varchar(300) NOT NULL,
  "news_time" timestamp without time zone NOT NULL,
  "title" varchar(300),
  "content" text,
  "keyword" varchar(500),
  "level" smallint NOT NULL DEFAULT 1,
  "stock_list" text,
  "image_urls" text,
  "raw_content" text,
  CONSTRAINT "spider_flash_news_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_flash_news_media_url" UNIQUE ("from_media", "news_url")
);

COMMENT ON TABLE "public"."spider_flash_news" IS '实时快讯 ( 列表即全文 , 入库即终态 )';
COMMENT ON COLUMN "public"."spider_flash_news"."level" IS '重要度 : 1 普通 / 2 重要 / 3 重大 ( 各源映射见 docs/news-pipeline.md )';

-- 实时消费热路径 : 各源最新一条 ( 滞后监控 ) 与按源取最近快讯
CREATE INDEX IF NOT EXISTS "idx_flash_news_media_time"
  ON "public"."spider_flash_news" ("from_media", "news_time");

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_flash_news FOR EACH ROW EXECUTE FUNCTION update_time_func();

-- 新闻流水线轮询部分索引 ( 老库由启动时 Pg.EnsureSpiderNewsListDbObjects 幂等补齐 )
CREATE INDEX IF NOT EXISTS "idx_news_list_download_status"
  ON "public"."spider_news_list" ("download_status_code", "id")
  WHERE download_status_code IN (0, 2, 3, 4);
