-- Database export: k_script_spider
-- Date: 2026-09-19 20:50:07
-- Generated by DBX

CREATE EXTENSION IF NOT EXISTS "amcheck" WITH SCHEMA "public";

DROP TABLE IF EXISTS "public"."spider_news_content" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_content_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_content" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300),
  "news_title" character varying(300),
  "news_summary" text,
  "news_from" character varying(100),
  "news_time" timestamp without time zone,
  "news_keyword" text,
  "news_content_json" text,
  "news_content_text" text,
  CONSTRAINT "spider_news_content_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_content_test_url" UNIQUE (news_url)
);
COMMENT ON TABLE "public"."spider_news_content" IS '新闻信息详情表';

DROP TABLE IF EXISTS "public"."spider_news_content_origin" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_content_origin_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_content_origin" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300) NOT NULL,
  "news_origin_content" text,
  "news_origin_type" integer NOT NULL DEFAULT 0,
  "status" integer NOT NULL DEFAULT 0,
  "message" text,
  CONSTRAINT "spider_news_content_origin_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_content_origin_url" UNIQUE (news_url)
);

DROP TABLE IF EXISTS "public"."spider_news_image_list" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_image_list_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_image_list" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300),
  "image_resource_url" character varying(400),
  "image_name" character varying(100),
  CONSTRAINT "spider_news_image_list_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_image_url" UNIQUE (image_resource_url)
);
COMMENT ON TABLE "public"."spider_news_image_list" IS '爬虫详情中的图片信息记录';

DROP TABLE IF EXISTS "public"."spider_news_list" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_list_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_list" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "from_media" integer,
  "news_url" character varying(300),
  "news_title" character varying(300),
  "news_summary" text,
  "news_from" character varying(30),
  "news_time" timestamp without time zone,
  "news_download_time" timestamp without time zone,
  "category" integer NOT NULL DEFAULT 0,
  "download_status_code" integer NOT NULL DEFAULT 0,
  "fail_count" integer NOT NULL DEFAULT 0,
  CONSTRAINT "spider_news_list_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_url" UNIQUE (news_url)
);
COMMENT ON TABLE "public"."spider_news_list" IS '排重抓取信息信息列表';
COMMENT ON COLUMN "public"."spider_news_list"."category" IS '新闻类型';
COMMENT ON COLUMN "public"."spider_news_list"."download_status_code" IS '详情数据是否下载 0 没有下载 1 已下载';
CREATE INDEX "idx_news_list_download_status" ON "public"."spider_news_list" USING btree ("download_status_code", "id") WHERE (download_status_code = ANY (ARRAY[0, 2, 3, 4]));

ALTER SEQUENCE "public"."spider_news_content_id_seq" OWNED BY "public"."spider_news_content"."id";

ALTER SEQUENCE "public"."spider_news_content_origin_id_seq" OWNED BY "public"."spider_news_content_origin"."id";

ALTER SEQUENCE "public"."spider_news_image_list_id_seq" OWNED BY "public"."spider_news_image_list"."id";

ALTER SEQUENCE "public"."spider_news_list_id_seq" OWNED BY "public"."spider_news_list"."id";

SELECT setval('"public"."spider_news_content_id_seq"', GREATEST(COALESCE(MAX("id"), 1254085), 1254085), true) FROM "public"."spider_news_content";

SELECT setval('"public"."spider_news_content_origin_id_seq"', GREATEST(COALESCE(MAX("id"), 991189), 991189), true) FROM "public"."spider_news_content_origin";

SELECT setval('"public"."spider_news_image_list_id_seq"', GREATEST(COALESCE(MAX("id"), 98564), 98564), true) FROM "public"."spider_news_image_list";

SELECT setval('"public"."spider_news_list_id_seq"', GREATEST(COALESCE(MAX("id"), 990191), 990191), true) FROM "public"."spider_news_list";

CREATE OR REPLACE FUNCTION public.update_time_func()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    NEW.update_time := current_timestamp;
    RETURN NEW;
END;$function$;

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_content FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_content_origin FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_image_list FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_list FOR EACH ROW EXECUTE FUNCTION update_time_func();

--
-- 实时快讯 ( 2026-09 新增 : 列表即全文的快讯源 , 拉到即终态 , 无状态机 )
--

CREATE TABLE IF NOT EXISTS "public"."spider_flash_news" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "from_media" integer NOT NULL,
  "category" integer NOT NULL DEFAULT 0,
  "news_url" varchar(300) NOT NULL,
  "news_time" timestamp without time zone NOT NULL,
  "title" varchar(300),
  "content" text,
  "keyword" varchar(500),
  "level" smallint NOT NULL DEFAULT 1,
  "stock_list" text,
  "image_urls" text,
  "raw_content" text,
  CONSTRAINT "spider_flash_news_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_flash_news_media_url" UNIQUE ("from_media", "news_url")
);

COMMENT ON TABLE "public"."spider_flash_news" IS '实时快讯 ( 列表即全文 , 入库即终态 )';
COMMENT ON COLUMN "public"."spider_flash_news"."level" IS '重要度 : 1 普通 / 2 重要 / 3 重大 ( 各源映射见 docs/news-pipeline.md )';

-- 实时消费热路径 : 各源最新一条 ( 滞后监控 ) 与按源取最近快讯
CREATE INDEX IF NOT EXISTS "idx_flash_news_media_time"
  ON "public"."spider_flash_news" ("from_media", "news_time");

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_flash_news FOR EACH ROW EXECUTE FUNCTION update_time_func();

-- 研报 ( 2026-09 新增 : 东财研报中心个股/行业/宏观三类 , 列表即结构化元数据直写 ,
-- 摘要正文由详情页二段回填 , 无状态机 ) ; 第三条管线专属表 , 不入新闻三表
CREATE TABLE IF NOT EXISTS "public"."spider_research_report" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "info_code" varchar(64) NOT NULL,
  "from_media" integer NOT NULL,
  "report_kind" smallint NOT NULL,
  "title" varchar(500) NOT NULL,
  "stock_code" varchar(32),
  "stock_name" varchar(64),
  "org_name" varchar(128),
  "rating_name" varchar(32),
  "industry_name" varchar(64),
  "aim_price_high" numeric(12,2),
  "aim_price_low" numeric(12,2),
  "eps_this_year" numeric(12,4),
  "pe_this_year" numeric(12,2),
  "eps_next_year" numeric(12,4),
  "pe_next_year" numeric(12,2),
  "researcher" varchar(200),
  "summary" text,
  "summary_fail_count" integer NOT NULL DEFAULT 0,
  "publish_date" timestamp without time zone NOT NULL,
  "raw_content" text,
  CONSTRAINT "spider_research_report_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_research_report_info_code" UNIQUE ("info_code")
);

COMMENT ON TABLE "public"."spider_research_report" IS '研报 ( 东财研报中心 , 列表即元数据 , 摘要由详情页回填 )';
COMMENT ON COLUMN "public"."spider_research_report"."info_code" IS '东财研报唯一标识 ( 如 AP202609301830020241 ) , 去重键';
COMMENT ON COLUMN "public"."spider_research_report"."report_kind" IS '研报类型 : 1 个股 / 2 行业 / 3 宏观 ( 对应接口 qType 0/1/2 )';
COMMENT ON COLUMN "public"."spider_research_report"."publish_date" IS '发布日期 ( 接口只到日期级 , 时间恒为 00:00:00 )';
COMMENT ON COLUMN "public"."spider_research_report"."summary" IS '摘要正文 ( 详情页 ctx-content 区纯文本 , 二段回填 )';
COMMENT ON COLUMN "public"."spider_research_report"."summary_fail_count" IS '摘要回填失败次数 ( 达上限 3 后不再重试 )';

-- 按发布日查询 ( 列表/分析 )
CREATE INDEX IF NOT EXISTS "idx_research_report_publish_date"
  ON "public"."spider_research_report" ("publish_date");

-- 摘要回填热路径 : 只扫待回填且未达失败上限的行 ( ResearchReportJob 每 5 分钟限量取一批 )
CREATE INDEX IF NOT EXISTS "idx_research_report_pending_summary"
  ON "public"."spider_research_report" ("id") WHERE summary IS NULL AND summary_fail_count < 3;

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_research_report FOR EACH ROW EXECUTE FUNCTION update_time_func();

-- 盘面榜单 ( 2026-09 新增 : Ranking 管线 , 东财数据中心 reportName 接口族 ,
-- 龙虎榜/大宗交易/两融三类 , 行即数值发布即终态 ; 契约见 docs/architecture.md )
CREATE TABLE IF NOT EXISTS "public"."spider_ranking" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ranking_type" smallint NOT NULL,
  "trade_date" date NOT NULL,
  "row_key" varchar(180) NOT NULL,
  "from_media" integer NOT NULL,
  "stock_code" varchar(16),
  "stock_name" varchar(64),
  "market" varchar(40),
  "close_price" numeric(12,3),
  "change_rate" numeric(10,4),
  "deal_amount" numeric(20,2),
  "net_amount" numeric(20,2),
  "buy_amount" numeric(20,2),
  "sell_amount" numeric(20,2),
  "detail" jsonb,
  "raw_content" text,
  CONSTRAINT "spider_ranking_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_ranking_type_date_row" UNIQUE ("ranking_type", "trade_date", "row_key")
);

COMMENT ON TABLE "public"."spider_ranking" IS '盘面榜单 ( 龙虎榜/大宗/两融 , 行即数值发布即终态 )';
COMMENT ON COLUMN "public"."spider_ranking"."ranking_type" IS '榜单类型 : 1 龙虎榜 / 2 大宗交易 / 3 两融 / 4 北向 ( 预留 )';
COMMENT ON COLUMN "public"."spider_ranking"."row_key" IS '类型内自然键 ( 龙虎榜=代码+上榜原因 / 大宗=代码+买卖营业部+价格 / 两融=代码 )';
COMMENT ON COLUMN "public"."spider_ranking"."trade_date" IS '交易日 ( 数据所属日期 , 非披露日 )';
COMMENT ON COLUMN "public"."spider_ranking"."detail" IS '类型特有长尾字段 ( JSONB : 龙虎榜后市表现/大宗买卖营业部/两融余额等 )';

-- 按类型与交易日查询 ( 榜单列表 )
CREATE INDEX IF NOT EXISTS "idx_ranking_type_date"
  ON "public"."spider_ranking" ("ranking_type", "trade_date" DESC);

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_ranking FOR EACH ROW EXECUTE FUNCTION update_time_func();

-- 公告 ( 2026-09 新增 : Announcement 管线 , 巨潮资讯沪深京法定披露 ,
-- 结构化文档元数据 : 证券+标题+分类+PDF 链接 , 披露即终态 ; 契约见 docs/architecture.md )
CREATE TABLE IF NOT EXISTS "public"."spider_announcement" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "announcement_id" varchar(64) NOT NULL,
  "from_media" integer NOT NULL,
  "sec_code" varchar(16),
  "sec_name" varchar(64),
  "category" varchar(200),
  "title" varchar(500) NOT NULL,
  "pdf_url" varchar(500),
  "publish_time" timestamp without time zone NOT NULL,
  "raw_content" text,
  CONSTRAINT "spider_announcement_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_announcement_id" UNIQUE ("announcement_id")
);

COMMENT ON TABLE "public"."spider_announcement" IS '公告 ( 巨潮资讯法定披露 , 文档元数据 , 披露即终态 )';
COMMENT ON COLUMN "public"."spider_announcement"."announcement_id" IS '站内公告唯一标识 ( 巨潮 announcementId ) , 去重键';
COMMENT ON COLUMN "public"."spider_announcement"."category" IS '公告分类 ( 巨潮 announcementType 代码串 , 对照巨潮分类表解读 )';
COMMENT ON COLUMN "public"."spider_announcement"."pdf_url" IS 'PDF 附件完整地址 ( 链接即交付物 , 不下载 )';

-- 按披露时间查询 ( 公告列表 )
CREATE INDEX IF NOT EXISTS "idx_announcement_publish_time"
  ON "public"."spider_announcement" ("publish_time" DESC);

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_announcement FOR EACH ROW EXECUTE FUNCTION update_time_func();

-- 新闻流水线轮询部分索引 ( 老库由启动时 Pg.EnsureSpiderNewsListDbObjects 幂等补齐 )
CREATE INDEX IF NOT EXISTS "idx_news_list_download_status"
  ON "public"."spider_news_list" ("download_status_code", "id")
  WHERE download_status_code IN (0, 2, 3, 4);

-- origin 解析路由标记 ( 2026-09 增量演进 : origin 表自包含 , 重放作业按行路由解析方法 )
-- from_media 冗余自列表行 ; parser_code 空 = 存量行回退按 from_media 走注册表
ALTER TABLE "public"."spider_news_content_origin" ADD COLUMN IF NOT EXISTS "from_media" integer NOT NULL DEFAULT 0;
ALTER TABLE "public"."spider_news_content_origin" ADD COLUMN IF NOT EXISTS "parser_code" text;
COMMENT ON COLUMN "public"."spider_news_content_origin"."from_media" IS '媒体标识 ( 下载时冗余自列表行 , origin 自包含路由用 )';
COMMENT ON COLUMN "public"."spider_news_content_origin"."parser_code" IS '解析器标识 ( 如 wscn-article-v1 ) , 空则回退按 from_media 路由';

-- 付费内容标记 ( 2026-09 增量演进 : 列表与原始内容两表同语义 , 无此信息的源恒为 false )
ALTER TABLE "public"."spider_news_list" ADD COLUMN IF NOT EXISTS "is_paid" boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN "public"."spider_news_list"."is_paid" IS '是否付费/会员专享内容 ( 列表接口侧标记 )';
ALTER TABLE "public"."spider_news_content_origin" ADD COLUMN IF NOT EXISTS "is_paid" boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN "public"."spider_news_content_origin"."is_paid" IS '原始内容是否来自付费文章 ( 详情侧标记 )';

-- 数据重放任务记录 ( k-spider-web 的重放工具落档 : 筛选条件 / 进度 / 结果 )
CREATE TABLE IF NOT EXISTS "public"."spider_replay_log" (
  "id" bigserial NOT NULL,
  "filter" text,
  "status" text NOT NULL DEFAULT 'running',
  "total" integer NOT NULL DEFAULT 0,
  "success_count" integer NOT NULL DEFAULT 0,
  "fail_count" integer NOT NULL DEFAULT 0,
  "message" text,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "finish_time" timestamp without time zone,
  CONSTRAINT "spider_replay_log_pkey" PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."spider_replay_log" IS '数据重放任务 ( Web 控制台发起 , origin 重新解析生成 content )';
CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_replay_log FOR EACH ROW EXECUTE FUNCTION update_time_func();

--
-- 系统运行状态表 ( 2026-09 新增 : Web 控制台 ( k-spider-web ) 的跨进程状态与指令通道 ;
-- 主程序上报 / 消费 , k-spider-web 读取展示与写入指令 , 老库由启动时 Pg.EnsureSystemDbObjects 幂等补齐 )
--

-- 任务调度态 : 每节点每任务一行 ( upsert 不膨胀 ) ; 执行列由 JobRuntimeListener 写 , 调度列由 NodeStateJob 刷新
CREATE TABLE IF NOT EXISTS "public"."spider_job_state" (
  "node_id" text NOT NULL,
  "job_name" text NOT NULL,
  "next_fire_time" timestamp without time zone,
  "is_paused" boolean NOT NULL DEFAULT false,
  "last_fired_at" timestamp without time zone,
  "last_duration_ms" bigint,
  "last_success" boolean,
  "consecutive_failures" integer NOT NULL DEFAULT 0,
  "last_error" text,
  "last_stats" text,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "spider_job_state_pkey" PRIMARY KEY ("node_id", "job_name")
);

COMMENT ON TABLE "public"."spider_job_state" IS '任务调度态 ( 执行结果 + 调度列 , 控制台展示 )';
COMMENT ON COLUMN "public"."spider_job_state"."last_stats" IS '上次执行摘要 ( 如 新增列表 12 )';

-- 任务指令 : k-spider-web 写 pending , 爬虫节点由 NodeStateJob 轮询消费后回写 done / rejected
CREATE TABLE IF NOT EXISTS "public"."spider_job_command" (
  "id" bigserial NOT NULL,
  "node_id" text,
  "job_name" text NOT NULL,
  "action" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "result" text,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "consumed_at" timestamp without time zone,
  CONSTRAINT "spider_job_command_pkey" PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."spider_job_command" IS '任务指令 ( trigger / pause / resume , Web → 爬虫 的控制通道 )';
COMMENT ON COLUMN "public"."spider_job_command"."node_id" IS '目标节点 , 空 = 任意节点 ( 分布式时的路由依据 )';

-- 指令轮询热路径 : 只扫 pending ( NodeStateJob 每 3 秒 )
CREATE INDEX IF NOT EXISTS "idx_job_command_pending"
  ON "public"."spider_job_command" ("id") WHERE status = 'pending';

-- 节点状态快照 : NewsCheckJob 每轮 upsert ( 接口探测 / 管线积压 / 快讯滞后 / 验证冷却 )
CREATE TABLE IF NOT EXISTS "public"."spider_node_status" (
  "node_id" text NOT NULL,
  "report_time" timestamp without time zone NOT NULL,
  "payload" text,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "spider_node_status_pkey" PRIMARY KEY ("node_id")
);

COMMENT ON TABLE "public"."spider_node_status" IS '节点状态快照 ( payload 为 JSON 文本 , report_time 过远即节点失联 )';

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_job_state FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_job_command FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_node_status FOR EACH ROW EXECUTE FUNCTION update_time_func();
