-- Database export: k_script_spider
-- Date: 2026-09-19 20:50:07
-- Generated by DBX

CREATE EXTENSION IF NOT EXISTS "amcheck" WITH SCHEMA "public";

DROP TABLE IF EXISTS "public"."spider_news_content" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_content_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_content" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300),
  "news_title" character varying(300),
  "news_summary" text,
  "news_from" character varying(100),
  "news_time" timestamp without time zone,
  "news_keyword" text,
  "news_content_json" text,
  "news_content_text" text,
  CONSTRAINT "spider_news_content_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_content_test_url" UNIQUE (news_url)
);
COMMENT ON TABLE "public"."spider_news_content" IS '新闻信息详情表';

DROP TABLE IF EXISTS "public"."spider_news_content_origin" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_content_origin_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_content_origin" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300) NOT NULL,
  "news_origin_content" text,
  "news_origin_type" integer NOT NULL DEFAULT 0,
  "status" integer NOT NULL DEFAULT 0,
  "message" text,
  CONSTRAINT "spider_news_content_origin_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_content_origin_url" UNIQUE (news_url)
);

DROP TABLE IF EXISTS "public"."spider_news_image_list" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_image_list_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_image_list" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "news_url" character varying(300),
  "image_resource_url" character varying(400),
  "image_name" character varying(100),
  CONSTRAINT "spider_news_image_list_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_image_url" UNIQUE (image_resource_url)
);
COMMENT ON TABLE "public"."spider_news_image_list" IS '爬虫详情中的图片信息记录';

DROP TABLE IF EXISTS "public"."spider_news_list" CASCADE;

CREATE SEQUENCE IF NOT EXISTS "public"."spider_news_list_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."spider_news_list" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "from_media" integer,
  "news_url" character varying(300),
  "news_title" character varying(300),
  "news_summary" text,
  "news_from" character varying(30),
  "news_time" timestamp without time zone,
  "news_download_time" timestamp without time zone,
  "category" integer NOT NULL DEFAULT 0,
  "download_status_code" integer NOT NULL DEFAULT 0,
  "fail_count" integer NOT NULL DEFAULT 0,
  CONSTRAINT "spider_news_list_pkey" PRIMARY KEY (id),
  CONSTRAINT "uk_news_url" UNIQUE (news_url)
);
COMMENT ON TABLE "public"."spider_news_list" IS '排重抓取信息信息列表';
COMMENT ON COLUMN "public"."spider_news_list"."category" IS '新闻类型';
COMMENT ON COLUMN "public"."spider_news_list"."download_status_code" IS '详情数据是否下载 0 没有下载 1 已下载';
CREATE INDEX "idx_news_list_download_status" ON "public"."spider_news_list" USING btree ("download_status_code", "id") WHERE (download_status_code = ANY (ARRAY[0, 2, 3, 4]));

ALTER SEQUENCE "public"."spider_news_content_id_seq" OWNED BY "public"."spider_news_content"."id";

ALTER SEQUENCE "public"."spider_news_content_origin_id_seq" OWNED BY "public"."spider_news_content_origin"."id";

ALTER SEQUENCE "public"."spider_news_image_list_id_seq" OWNED BY "public"."spider_news_image_list"."id";

ALTER SEQUENCE "public"."spider_news_list_id_seq" OWNED BY "public"."spider_news_list"."id";

SELECT setval('"public"."spider_news_content_id_seq"', GREATEST(COALESCE(MAX("id"), 1254085), 1254085), true) FROM "public"."spider_news_content";

SELECT setval('"public"."spider_news_content_origin_id_seq"', GREATEST(COALESCE(MAX("id"), 991189), 991189), true) FROM "public"."spider_news_content_origin";

SELECT setval('"public"."spider_news_image_list_id_seq"', GREATEST(COALESCE(MAX("id"), 98564), 98564), true) FROM "public"."spider_news_image_list";

SELECT setval('"public"."spider_news_list_id_seq"', GREATEST(COALESCE(MAX("id"), 990191), 990191), true) FROM "public"."spider_news_list";

CREATE OR REPLACE FUNCTION public.update_time_func()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    NEW.update_time := current_timestamp;
    RETURN NEW;
END;$function$;

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_content FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_content_origin FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_image_list FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_news_list FOR EACH ROW EXECUTE FUNCTION update_time_func();

--
-- 实时快讯 ( 2026-09 新增 : 列表即全文的快讯源 , 拉到即终态 , 无状态机 )
--

CREATE TABLE IF NOT EXISTS "public"."spider_flash_news" (
  "id" bigserial NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "from_media" integer NOT NULL,
  "category" integer NOT NULL DEFAULT 0,
  "news_url" varchar(300) NOT NULL,
  "news_time" timestamp without time zone NOT NULL,
  "title" varchar(300),
  "content" text,
  "keyword" varchar(500),
  "level" smallint NOT NULL DEFAULT 1,
  "stock_list" text,
  "image_urls" text,
  "raw_content" text,
  CONSTRAINT "spider_flash_news_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_flash_news_media_url" UNIQUE ("from_media", "news_url")
);

COMMENT ON TABLE "public"."spider_flash_news" IS '实时快讯 ( 列表即全文 , 入库即终态 )';
COMMENT ON COLUMN "public"."spider_flash_news"."level" IS '重要度 : 1 普通 / 2 重要 / 3 重大 ( 各源映射见 docs/news-pipeline.md )';

-- 实时消费热路径 : 各源最新一条 ( 滞后监控 ) 与按源取最近快讯
CREATE INDEX IF NOT EXISTS "idx_flash_news_media_time"
  ON "public"."spider_flash_news" ("from_media", "news_time");

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_flash_news FOR EACH ROW EXECUTE FUNCTION update_time_func();

-- 新闻流水线轮询部分索引 ( 老库由启动时 Pg.EnsureSpiderNewsListDbObjects 幂等补齐 )
CREATE INDEX IF NOT EXISTS "idx_news_list_download_status"
  ON "public"."spider_news_list" ("download_status_code", "id")
  WHERE download_status_code IN (0, 2, 3, 4);

-- 付费内容标记 ( 2026-09 增量演进 : 列表与原始内容两表同语义 , 无此信息的源恒为 false )
ALTER TABLE "public"."spider_news_list" ADD COLUMN IF NOT EXISTS "is_paid" boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN "public"."spider_news_list"."is_paid" IS '是否付费/会员专享内容 ( 列表接口侧标记 )';
ALTER TABLE "public"."spider_news_content_origin" ADD COLUMN IF NOT EXISTS "is_paid" boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN "public"."spider_news_content_origin"."is_paid" IS '原始内容是否来自付费文章 ( 详情侧标记 )';

--
-- 系统运行状态表 ( 2026-09 新增 : Web 控制台 ( k-spider-web ) 的跨进程状态与指令通道 ;
-- 主程序上报 / 消费 , k-spider-web 读取展示与写入指令 , 老库由启动时 Pg.EnsureSystemDbObjects 幂等补齐 )
--

-- 任务调度态 : 每节点每任务一行 ( upsert 不膨胀 ) ; 执行列由 JobRuntimeListener 写 , 调度列由 NodeStateJob 刷新
CREATE TABLE IF NOT EXISTS "public"."spider_job_state" (
  "node_id" text NOT NULL,
  "job_name" text NOT NULL,
  "next_fire_time" timestamp without time zone,
  "is_paused" boolean NOT NULL DEFAULT false,
  "last_fired_at" timestamp without time zone,
  "last_duration_ms" bigint,
  "last_success" boolean,
  "consecutive_failures" integer NOT NULL DEFAULT 0,
  "last_error" text,
  "last_stats" text,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "spider_job_state_pkey" PRIMARY KEY ("node_id", "job_name")
);

COMMENT ON TABLE "public"."spider_job_state" IS '任务调度态 ( 执行结果 + 调度列 , 控制台展示 )';
COMMENT ON COLUMN "public"."spider_job_state"."last_stats" IS '上次执行摘要 ( 如 新增列表 12 )';

-- 任务指令 : k-spider-web 写 pending , 爬虫节点由 NodeStateJob 轮询消费后回写 done / rejected
CREATE TABLE IF NOT EXISTS "public"."spider_job_command" (
  "id" bigserial NOT NULL,
  "node_id" text,
  "job_name" text NOT NULL,
  "action" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "result" text,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "consumed_at" timestamp without time zone,
  CONSTRAINT "spider_job_command_pkey" PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."spider_job_command" IS '任务指令 ( trigger / pause / resume , Web → 爬虫 的控制通道 )';
COMMENT ON COLUMN "public"."spider_job_command"."node_id" IS '目标节点 , 空 = 任意节点 ( 分布式时的路由依据 )';

-- 指令轮询热路径 : 只扫 pending ( NodeStateJob 每 3 秒 )
CREATE INDEX IF NOT EXISTS "idx_job_command_pending"
  ON "public"."spider_job_command" ("id") WHERE status = 'pending';

-- 节点状态快照 : NewsCheckJob 每轮 upsert ( 接口探测 / 管线积压 / 快讯滞后 / 验证冷却 )
CREATE TABLE IF NOT EXISTS "public"."spider_node_status" (
  "node_id" text NOT NULL,
  "report_time" timestamp without time zone NOT NULL,
  "payload" text,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "spider_node_status_pkey" PRIMARY KEY ("node_id")
);

COMMENT ON TABLE "public"."spider_node_status" IS '节点状态快照 ( payload 为 JSON 文本 , report_time 过远即节点失联 )';

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_job_state FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_job_command FOR EACH ROW EXECUTE FUNCTION update_time_func();

CREATE TRIGGER update_modified_column BEFORE UPDATE ON spider_node_status FOR EACH ROW EXECUTE FUNCTION update_time_func();
