<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>k_spider_dotnet</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
        <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
        <PackageReference Include="Quartz" Version="3.19.1" />
        <PackageReference Include="SqlSugarCore" Version="5.1.4.216" />
    </ItemGroup>
    <ItemGroup>
        <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
